[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
autoconfirm = true

[auth.jwt]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[database]
pool_mode = "transaction"
max_connections = 50
